// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: frequent_routes.
// - Entity ID: 102019b833baaa77907b04c13ea849cd848.
// - Entity Version: 102019bbffdfd9878649ac2b53a4b3cbf7b.
// - Task ID: 696872113388642b4ed48fda.
// - Task Root ID: 6958e27e4f7767272926ad86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for FrequentRoutesModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface FrequentRoutesModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  origin_name: string;
  origin_lat: number;
  origin_lng: number;
  destination_name: string;
  destination_lat: number;
  destination_lng: number;
  route_polyline: string;
  frequency_count: number;
  average_travel_time_seconds: number;
  last_accessed_time: string;
}

/**
 * ORM class for FrequentRoutes entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class FrequentRoutesORM {
  private static instance: FrequentRoutesORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b833baaa77907b04c13ea849cd848';
    this.entityName = 'frequent_routes';
    this.entityVersion = '102019bbffdfd9878649ac2b53a4b3cbf7b';
    this.taskId = '696872113388642b4ed48fda';
    this.taskRootId = '6958e27e4f7767272926ad86';
  }

  /**
   * Get singleton instance of FrequentRoutesORM
   */
  public static getInstance(): FrequentRoutesORM {
    if (!FrequentRoutesORM.instance) {
      FrequentRoutesORM.instance = new FrequentRoutesORM();
    }
    
    return FrequentRoutesORM.instance;
  }

  /**
   * Get frequent_routes by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getFrequentRoutesByIDs(ids: string[]): Promise<FrequentRoutesModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteFrequentRoutesByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all FrequentRoutes records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllFrequentRoutes(): Promise<FrequentRoutesModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new FrequentRoutes record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertFrequentRoutes(data: FrequentRoutesModel[]): Promise<FrequentRoutesModel[]> {
    const structured = data.map((item) => CreateData(FrequentRoutesModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all FrequentRoutes records
   */
  async purgeAllFrequentRoutes(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List FrequentRoutes records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listFrequentRoutes(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[FrequentRoutesModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get frequent_routes by Id index
   * This function gets data by index.
   */
  async getFrequentRoutesById(
    id: string,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesById(
    id: string,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexId(
      id
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by Id index
   */
  async deleteFrequentRoutesById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get frequent_routes by DestinationNameOriginName index
   * This function gets data by index.
   */
  async getFrequentRoutesByDestinationNameOriginName(
    destination_name: string,
    origin_name: string,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDestinationNameOriginName(
      destination_name,
      origin_name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by DestinationNameOriginName index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesByDestinationNameOriginName(
    destination_name: string,
    origin_name: string,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDestinationNameOriginName(
      destination_name,
      origin_name
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by DestinationNameOriginName index
   */
  async deleteFrequentRoutesByDestinationNameOriginName(
    destination_name: string,
    origin_name: string
  ): Promise<void> {
    const index = createIndexDestinationNameOriginName(
      destination_name,
      origin_name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get frequent_routes by FrequencyCount index
   * This function gets data by index.
   */
  async getFrequentRoutesByFrequencyCount(
    frequency_count: number,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexFrequencyCount(
      frequency_count
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by FrequencyCount index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesByFrequencyCount(
    frequency_count: number,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexFrequencyCount(
      frequency_count
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by FrequencyCount index
   */
  async deleteFrequentRoutesByFrequencyCount(
    frequency_count: number
  ): Promise<void> {
    const index = createIndexFrequencyCount(
      frequency_count
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get frequent_routes by LastAccessedTime index
   * This function gets data by index.
   */
  async getFrequentRoutesByLastAccessedTime(
    last_accessed_time: string,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexLastAccessedTime(
      last_accessed_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by LastAccessedTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesByLastAccessedTime(
    last_accessed_time: string,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexLastAccessedTime(
      last_accessed_time
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by LastAccessedTime index
   */
  async deleteFrequentRoutesByLastAccessedTime(
    last_accessed_time: string
  ): Promise<void> {
    const index = createIndexLastAccessedTime(
      last_accessed_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get frequent_routes by DataCreator index
   * This function gets data by index.
   */
  async getFrequentRoutesByDataCreator(
    data_creator: string,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesByDataCreator(
    data_creator: string,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by DataCreator index
   */
  async deleteFrequentRoutesByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get frequent_routes by DataUpdater index
   * This function gets data by index.
   */
  async getFrequentRoutesByDataUpdater(
    data_updater: string,
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) frequent_routes by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFrequentRoutesByDataUpdater(
    data_updater: string,
    data: FrequentRoutesModel
  ): Promise<FrequentRoutesModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = FrequentRoutesModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete frequent_routes by DataUpdater index
   */
  async deleteFrequentRoutesByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to FrequentRoutesModel data array
   */
  private resultToData(values: Data[]): FrequentRoutesModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return FrequentRoutesModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as FrequentRoutesModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized FrequentRoutesModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is FrequentRoutesModel => item !== null);
  }
}

/**
 * Convert FrequentRoutesModel data to Value array
 */
function FrequentRoutesModelToValues(data: FrequentRoutesModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'origin_name', type: DataType.string, defaultValue: '' },
    { key: 'origin_lat', type: DataType.number, defaultValue: 0 },
    { key: 'origin_lng', type: DataType.number, defaultValue: 0 },
    { key: 'destination_name', type: DataType.string, defaultValue: '' },
    { key: 'destination_lat', type: DataType.number, defaultValue: 0 },
    { key: 'destination_lng', type: DataType.number, defaultValue: 0 },
    { key: 'route_polyline', type: DataType.string, defaultValue: '' },
    { key: 'frequency_count', type: DataType.number, defaultValue: 0 },
    { key: 'average_travel_time_seconds', type: DataType.number, defaultValue: 0 },
    { key: 'last_accessed_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof FrequentRoutesModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to FrequentRoutesModel data
 */
function FrequentRoutesModelFromValues(values: Value[]): FrequentRoutesModel {
  const data: Partial<FrequentRoutesModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'origin_name':
        data.origin_name = ParseValue(value, DataType.string) as string;
        break;
      case 'origin_lat':
        data.origin_lat = ParseValue(value, DataType.number) as number;
        break;
      case 'origin_lng':
        data.origin_lng = ParseValue(value, DataType.number) as number;
        break;
      case 'destination_name':
        data.destination_name = ParseValue(value, DataType.string) as string;
        break;
      case 'destination_lat':
        data.destination_lat = ParseValue(value, DataType.number) as number;
        break;
      case 'destination_lng':
        data.destination_lng = ParseValue(value, DataType.number) as number;
        break;
      case 'route_polyline':
        data.route_polyline = ParseValue(value, DataType.string) as string;
        break;
      case 'frequency_count':
        data.frequency_count = ParseValue(value, DataType.number) as number;
        break;
      case 'average_travel_time_seconds':
        data.average_travel_time_seconds = ParseValue(value, DataType.number) as number;
        break;
      case 'last_accessed_time':
        data.last_accessed_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as FrequentRoutesModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DestinationNameOriginName fields
 */
function createIndexDestinationNameOriginName(
  destination_name: string,
  origin_name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, destination_name, 'destination_name'),
    CreateValue(DataType.string, origin_name, 'origin_name'),
  ];

  return {
    fields: ['destination_name', 'origin_name'],
    values
  };
}
/**
 * Create index for FrequencyCount fields
 */
function createIndexFrequencyCount(
  frequency_count: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, frequency_count, 'frequency_count'),
  ];

  return {
    fields: ['frequency_count'],
    values
  };
}
/**
 * Create index for LastAccessedTime fields
 */
function createIndexLastAccessedTime(
  last_accessed_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, last_accessed_time, 'last_accessed_time'),
  ];

  return {
    fields: ['last_accessed_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default FrequentRoutesORM;