// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_feedback.
// - Entity ID: 102019b9e8947ef7875b2697c575dc49f83.
// - Entity Version: 102019bbffdfd9878649ac2b53a4b3cbf7b.
// - Task ID: 696872113388642b4ed48fda.
// - Task Root ID: 6958e27e4f7767272926ad86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserFeedbackFeedbackType
 */
export enum UserFeedbackFeedbackType {
  Unspecified = 0,
  route_quality = 1,
  traffic_accuracy = 2,
  shortcut_suggestion = 3,
  other = 4,
}



/**
 * Interface for UserFeedbackModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserFeedbackModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  route_origin: string;
  route_destination: string;
  feedback_type: UserFeedbackFeedbackType;
  rating: number;
  comments?: string | null;
  created_at: string;
}

/**
 * ORM class for UserFeedback entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserFeedbackORM {
  private static instance: UserFeedbackORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b9e8947ef7875b2697c575dc49f83';
    this.entityName = 'user_feedback';
    this.entityVersion = '102019bbffdfd9878649ac2b53a4b3cbf7b';
    this.taskId = '696872113388642b4ed48fda';
    this.taskRootId = '6958e27e4f7767272926ad86';
  }

  /**
   * Get singleton instance of UserFeedbackORM
   */
  public static getInstance(): UserFeedbackORM {
    if (!UserFeedbackORM.instance) {
      UserFeedbackORM.instance = new UserFeedbackORM();
    }
    
    return UserFeedbackORM.instance;
  }

  /**
   * Get user_feedback by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserFeedbackByIDs(ids: string[]): Promise<UserFeedbackModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserFeedbackByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all UserFeedback records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserFeedback(): Promise<UserFeedbackModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserFeedback record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserFeedback(data: UserFeedbackModel[]): Promise<UserFeedbackModel[]> {
    const structured = data.map((item) => CreateData(UserFeedbackModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserFeedback records
   */
  async purgeAllUserFeedback(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserFeedback records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserFeedback(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserFeedbackModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_feedback by Id index
   * This function gets data by index.
   */
  async getUserFeedbackById(
    id: string,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackById(
    id: string,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by Id index
   */
  async deleteUserFeedbackById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by UserId index
   * This function gets data by index.
   */
  async getUserFeedbackByUserId(
    user_id: string,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByUserId(
    user_id: string,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by UserId index
   */
  async deleteUserFeedbackByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by CreatedAt index
   * This function gets data by index.
   */
  async getUserFeedbackByCreatedAt(
    created_at: string,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by CreatedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByCreatedAt(
    created_at: string,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by CreatedAt index
   */
  async deleteUserFeedbackByCreatedAt(
    created_at: string
  ): Promise<void> {
    const index = createIndexCreatedAt(
      created_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by FeedbackType index
   * This function gets data by index.
   */
  async getUserFeedbackByFeedbackType(
    feedback_type: UserFeedbackFeedbackType,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexFeedbackType(
      feedback_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by FeedbackType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByFeedbackType(
    feedback_type: UserFeedbackFeedbackType,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexFeedbackType(
      feedback_type
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by FeedbackType index
   */
  async deleteUserFeedbackByFeedbackType(
    feedback_type: UserFeedbackFeedbackType
  ): Promise<void> {
    const index = createIndexFeedbackType(
      feedback_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by Rating index
   * This function gets data by index.
   */
  async getUserFeedbackByRating(
    rating: number,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexRating(
      rating
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by Rating index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByRating(
    rating: number,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexRating(
      rating
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by Rating index
   */
  async deleteUserFeedbackByRating(
    rating: number
  ): Promise<void> {
    const index = createIndexRating(
      rating
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by DataCreator index
   * This function gets data by index.
   */
  async getUserFeedbackByDataCreator(
    data_creator: string,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByDataCreator(
    data_creator: string,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by DataCreator index
   */
  async deleteUserFeedbackByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_feedback by DataUpdater index
   * This function gets data by index.
   */
  async getUserFeedbackByDataUpdater(
    data_updater: string,
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_feedback by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFeedbackByDataUpdater(
    data_updater: string,
    data: UserFeedbackModel
  ): Promise<UserFeedbackModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserFeedbackModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_feedback by DataUpdater index
   */
  async deleteUserFeedbackByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserFeedbackModel data array
   */
  private resultToData(values: Data[]): UserFeedbackModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserFeedbackModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserFeedbackModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserFeedbackModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserFeedbackModel => item !== null);
  }
}

/**
 * Convert UserFeedbackModel data to Value array
 */
function UserFeedbackModelToValues(data: UserFeedbackModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'route_origin', type: DataType.string, defaultValue: '' },
    { key: 'route_destination', type: DataType.string, defaultValue: '' },
    { key: 'feedback_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'rating', type: DataType.number, defaultValue: 0 },
    { key: 'comments', type: DataType.string, defaultValue: null },
    { key: 'created_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserFeedbackModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserFeedbackModel data
 */
function UserFeedbackModelFromValues(values: Value[]): UserFeedbackModel {
  const data: Partial<UserFeedbackModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'route_origin':
        data.route_origin = ParseValue(value, DataType.string) as string;
        break;
      case 'route_destination':
        data.route_destination = ParseValue(value, DataType.string) as string;
        break;
      case 'feedback_type':
        data.feedback_type = ParseValue(value, DataType.enumeration) as UserFeedbackFeedbackType;
        break;
      case 'rating':
        data.rating = ParseValue(value, DataType.number) as number;
        break;
      case 'comments':
        data.comments = ParseValue(value, DataType.string) as string | null;
        break;
      case 'created_at':
        data.created_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as UserFeedbackModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CreatedAt fields
 */
function createIndexCreatedAt(
  created_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, created_at, 'created_at'),
  ];

  return {
    fields: ['created_at'],
    values
  };
}
/**
 * Create index for FeedbackType fields
 */
function createIndexFeedbackType(
  feedback_type: UserFeedbackFeedbackType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, feedback_type, 'feedback_type'),
  ];

  return {
    fields: ['feedback_type'],
    values
  };
}
/**
 * Create index for Rating fields
 */
function createIndexRating(
  rating: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, rating, 'rating'),
  ];

  return {
    fields: ['rating'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default UserFeedbackORM;