// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: training_submission.
// - Entity ID: 102019b9e8947ef757599a40cccdcaffccd.
// - Entity Version: 102019bbffdfd9878649ac2b53a4b3cbf7b.
// - Task ID: 696872113388642b4ed48fda.
// - Task Root ID: 6958e27e4f7767272926ad86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TrainingSubmissionTrafficLevel
 */
export enum TrainingSubmissionTrafficLevel {
  Unspecified = 0,
  low = 1,
  moderate = 2,
  high = 3,
}
/**
 * Enumeration for TrainingSubmissionTransportMode
 */
export enum TrainingSubmissionTransportMode {
  Unspecified = 0,
  driving = 1,
  cycling = 2,
  walking = 3,
  bus = 4,
  bike = 5,
}



/**
 * Interface for TrainingSubmissionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TrainingSubmissionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  route_name: string;
  predicted_time_minutes: number;
  actual_time_minutes: number;
  traffic_level: TrainingSubmissionTrafficLevel;
  transport_mode: TrainingSubmissionTransportMode;
  feedback_notes?: string | null;
  accuracy_score: number;
  submitted_at: string;
}

/**
 * ORM class for TrainingSubmission entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TrainingSubmissionORM {
  private static instance: TrainingSubmissionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b9e8947ef757599a40cccdcaffccd';
    this.entityName = 'training_submission';
    this.entityVersion = '102019bbffdfd9878649ac2b53a4b3cbf7b';
    this.taskId = '696872113388642b4ed48fda';
    this.taskRootId = '6958e27e4f7767272926ad86';
  }

  /**
   * Get singleton instance of TrainingSubmissionORM
   */
  public static getInstance(): TrainingSubmissionORM {
    if (!TrainingSubmissionORM.instance) {
      TrainingSubmissionORM.instance = new TrainingSubmissionORM();
    }
    
    return TrainingSubmissionORM.instance;
  }

  /**
   * Get training_submission by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getTrainingSubmissionByIDs(ids: string[]): Promise<TrainingSubmissionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteTrainingSubmissionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all TrainingSubmission records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTrainingSubmission(): Promise<TrainingSubmissionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TrainingSubmission record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTrainingSubmission(data: TrainingSubmissionModel[]): Promise<TrainingSubmissionModel[]> {
    const structured = data.map((item) => CreateData(TrainingSubmissionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TrainingSubmission records
   */
  async purgeAllTrainingSubmission(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TrainingSubmission records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTrainingSubmission(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TrainingSubmissionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get training_submission by Id index
   * This function gets data by index.
   */
  async getTrainingSubmissionById(
    id: string,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionById(
    id: string,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexId(
      id
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by Id index
   */
  async deleteTrainingSubmissionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by UserId index
   * This function gets data by index.
   */
  async getTrainingSubmissionByUserId(
    user_id: string,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByUserId(
    user_id: string,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by UserId index
   */
  async deleteTrainingSubmissionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by SubmittedAt index
   * This function gets data by index.
   */
  async getTrainingSubmissionBySubmittedAt(
    submitted_at: string,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by SubmittedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionBySubmittedAt(
    submitted_at: string,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by SubmittedAt index
   */
  async deleteTrainingSubmissionBySubmittedAt(
    submitted_at: string
  ): Promise<void> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by TrafficLevel index
   * This function gets data by index.
   */
  async getTrainingSubmissionByTrafficLevel(
    traffic_level: TrainingSubmissionTrafficLevel,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexTrafficLevel(
      traffic_level
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by TrafficLevel index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByTrafficLevel(
    traffic_level: TrainingSubmissionTrafficLevel,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexTrafficLevel(
      traffic_level
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by TrafficLevel index
   */
  async deleteTrainingSubmissionByTrafficLevel(
    traffic_level: TrainingSubmissionTrafficLevel
  ): Promise<void> {
    const index = createIndexTrafficLevel(
      traffic_level
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by TransportMode index
   * This function gets data by index.
   */
  async getTrainingSubmissionByTransportMode(
    transport_mode: TrainingSubmissionTransportMode,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexTransportMode(
      transport_mode
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by TransportMode index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByTransportMode(
    transport_mode: TrainingSubmissionTransportMode,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexTransportMode(
      transport_mode
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by TransportMode index
   */
  async deleteTrainingSubmissionByTransportMode(
    transport_mode: TrainingSubmissionTransportMode
  ): Promise<void> {
    const index = createIndexTransportMode(
      transport_mode
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by AccuracyScore index
   * This function gets data by index.
   */
  async getTrainingSubmissionByAccuracyScore(
    accuracy_score: number,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexAccuracyScore(
      accuracy_score
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by AccuracyScore index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByAccuracyScore(
    accuracy_score: number,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexAccuracyScore(
      accuracy_score
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by AccuracyScore index
   */
  async deleteTrainingSubmissionByAccuracyScore(
    accuracy_score: number
  ): Promise<void> {
    const index = createIndexAccuracyScore(
      accuracy_score
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by DataCreator index
   * This function gets data by index.
   */
  async getTrainingSubmissionByDataCreator(
    data_creator: string,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByDataCreator(
    data_creator: string,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by DataCreator index
   */
  async deleteTrainingSubmissionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_submission by DataUpdater index
   * This function gets data by index.
   */
  async getTrainingSubmissionByDataUpdater(
    data_updater: string,
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_submission by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSubmissionByDataUpdater(
    data_updater: string,
    data: TrainingSubmissionModel
  ): Promise<TrainingSubmissionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TrainingSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_submission by DataUpdater index
   */
  async deleteTrainingSubmissionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TrainingSubmissionModel data array
   */
  private resultToData(values: Data[]): TrainingSubmissionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TrainingSubmissionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TrainingSubmissionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TrainingSubmissionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TrainingSubmissionModel => item !== null);
  }
}

/**
 * Convert TrainingSubmissionModel data to Value array
 */
function TrainingSubmissionModelToValues(data: TrainingSubmissionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'route_name', type: DataType.string, defaultValue: '' },
    { key: 'predicted_time_minutes', type: DataType.number, defaultValue: 0 },
    { key: 'actual_time_minutes', type: DataType.number, defaultValue: 0 },
    { key: 'traffic_level', type: DataType.enumeration, defaultValue: 0 },
    { key: 'transport_mode', type: DataType.enumeration, defaultValue: 0 },
    { key: 'feedback_notes', type: DataType.string, defaultValue: null },
    { key: 'accuracy_score', type: DataType.number, defaultValue: 0 },
    { key: 'submitted_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TrainingSubmissionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TrainingSubmissionModel data
 */
function TrainingSubmissionModelFromValues(values: Value[]): TrainingSubmissionModel {
  const data: Partial<TrainingSubmissionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'route_name':
        data.route_name = ParseValue(value, DataType.string) as string;
        break;
      case 'predicted_time_minutes':
        data.predicted_time_minutes = ParseValue(value, DataType.number) as number;
        break;
      case 'actual_time_minutes':
        data.actual_time_minutes = ParseValue(value, DataType.number) as number;
        break;
      case 'traffic_level':
        data.traffic_level = ParseValue(value, DataType.enumeration) as TrainingSubmissionTrafficLevel;
        break;
      case 'transport_mode':
        data.transport_mode = ParseValue(value, DataType.enumeration) as TrainingSubmissionTransportMode;
        break;
      case 'feedback_notes':
        data.feedback_notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'accuracy_score':
        data.accuracy_score = ParseValue(value, DataType.number) as number;
        break;
      case 'submitted_at':
        data.submitted_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as TrainingSubmissionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for SubmittedAt fields
 */
function createIndexSubmittedAt(
  submitted_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, submitted_at, 'submitted_at'),
  ];

  return {
    fields: ['submitted_at'],
    values
  };
}
/**
 * Create index for TrafficLevel fields
 */
function createIndexTrafficLevel(
  traffic_level: TrainingSubmissionTrafficLevel
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, traffic_level, 'traffic_level'),
  ];

  return {
    fields: ['traffic_level'],
    values
  };
}
/**
 * Create index for TransportMode fields
 */
function createIndexTransportMode(
  transport_mode: TrainingSubmissionTransportMode
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, transport_mode, 'transport_mode'),
  ];

  return {
    fields: ['transport_mode'],
    values
  };
}
/**
 * Create index for AccuracyScore fields
 */
function createIndexAccuracyScore(
  accuracy_score: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, accuracy_score, 'accuracy_score'),
  ];

  return {
    fields: ['accuracy_score'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TrainingSubmissionORM;