// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user.
// - Entity ID: 102019b9e8947ef72918e2e143b21504e04.
// - Entity Version: 102019bbffdfd9878649ac2b53a4b3cbf7b.
// - Task ID: 696872113388642b4ed48fda.
// - Task Root ID: 6958e27e4f7767272926ad86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  google_id?: string | null;
  apple_id?: string | null;
  email: string;
  name: string;
  avatar?: string | null;
  created_at: string;
  last_login: string;
}

/**
 * ORM class for User entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserORM {
  private static instance: UserORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b9e8947ef72918e2e143b21504e04';
    this.entityName = 'user';
    this.entityVersion = '102019bbffdfd9878649ac2b53a4b3cbf7b';
    this.taskId = '696872113388642b4ed48fda';
    this.taskRootId = '6958e27e4f7767272926ad86';
  }

  /**
   * Get singleton instance of UserORM
   */
  public static getInstance(): UserORM {
    if (!UserORM.instance) {
      UserORM.instance = new UserORM();
    }
    
    return UserORM.instance;
  }

  /**
   * Get user by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserByIDs(ids: string[]): Promise<UserModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all User records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUser(): Promise<UserModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new User record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUser(data: UserModel[]): Promise<UserModel[]> {
    const structured = data.map((item) => CreateData(UserModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all User records
   */
  async purgeAllUser(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List User records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUser(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user by Id index
   * This function gets data by index.
   */
  async getUserById(
    id: string,
  ): Promise<UserModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserById(
    id: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by Id index
   */
  async deleteUserById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by GoogleId index
   * This function gets data by index.
   */
  async getUserByGoogleId(
    google_id: string,
  ): Promise<UserModel[]> {
    const index = createIndexGoogleId(
      google_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by GoogleId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByGoogleId(
    google_id: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexGoogleId(
      google_id
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by GoogleId index
   */
  async deleteUserByGoogleId(
    google_id: string
  ): Promise<void> {
    const index = createIndexGoogleId(
      google_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by AppleId index
   * This function gets data by index.
   */
  async getUserByAppleId(
    apple_id: string,
  ): Promise<UserModel[]> {
    const index = createIndexAppleId(
      apple_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by AppleId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByAppleId(
    apple_id: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexAppleId(
      apple_id
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by AppleId index
   */
  async deleteUserByAppleId(
    apple_id: string
  ): Promise<void> {
    const index = createIndexAppleId(
      apple_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by Email index
   * This function gets data by index.
   */
  async getUserByEmail(
    email: string,
  ): Promise<UserModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByEmail(
    email: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by Email index
   */
  async deleteUserByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by CreatedAt index
   * This function gets data by index.
   */
  async getUserByCreatedAt(
    created_at: string,
  ): Promise<UserModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by CreatedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByCreatedAt(
    created_at: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexCreatedAt(
      created_at
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by CreatedAt index
   */
  async deleteUserByCreatedAt(
    created_at: string
  ): Promise<void> {
    const index = createIndexCreatedAt(
      created_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by LastLogin index
   * This function gets data by index.
   */
  async getUserByLastLogin(
    last_login: string,
  ): Promise<UserModel[]> {
    const index = createIndexLastLogin(
      last_login
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by LastLogin index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByLastLogin(
    last_login: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexLastLogin(
      last_login
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by LastLogin index
   */
  async deleteUserByLastLogin(
    last_login: string
  ): Promise<void> {
    const index = createIndexLastLogin(
      last_login
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by DataCreator index
   * This function gets data by index.
   */
  async getUserByDataCreator(
    data_creator: string,
  ): Promise<UserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByDataCreator(
    data_creator: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by DataCreator index
   */
  async deleteUserByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user by DataUpdater index
   * This function gets data by index.
   */
  async getUserByDataUpdater(
    data_updater: string,
  ): Promise<UserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserByDataUpdater(
    data_updater: string,
    data: UserModel
  ): Promise<UserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user by DataUpdater index
   */
  async deleteUserByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserModel data array
   */
  private resultToData(values: Data[]): UserModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserModel => item !== null);
  }
}

/**
 * Convert UserModel data to Value array
 */
function UserModelToValues(data: UserModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'google_id', type: DataType.string, defaultValue: null },
    { key: 'apple_id', type: DataType.string, defaultValue: null },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'avatar', type: DataType.string, defaultValue: null },
    { key: 'created_at', type: DataType.string, defaultValue: '' },
    { key: 'last_login', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserModel data
 */
function UserModelFromValues(values: Value[]): UserModel {
  const data: Partial<UserModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'google_id':
        data.google_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'apple_id':
        data.apple_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'avatar':
        data.avatar = ParseValue(value, DataType.string) as string | null;
        break;
      case 'created_at':
        data.created_at = ParseValue(value, DataType.string) as string;
        break;
      case 'last_login':
        data.last_login = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as UserModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for GoogleId fields
 */
function createIndexGoogleId(
  google_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, google_id, 'google_id'),
  ];

  return {
    fields: ['google_id'],
    values
  };
}
/**
 * Create index for AppleId fields
 */
function createIndexAppleId(
  apple_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, apple_id, 'apple_id'),
  ];

  return {
    fields: ['apple_id'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for CreatedAt fields
 */
function createIndexCreatedAt(
  created_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, created_at, 'created_at'),
  ];

  return {
    fields: ['created_at'],
    values
  };
}
/**
 * Create index for LastLogin fields
 */
function createIndexLastLogin(
  last_login: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, last_login, 'last_login'),
  ];

  return {
    fields: ['last_login'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default UserORM;