// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: search_history.
// - Entity ID: 102019b833baaa77582942bb34d2683e028.
// - Entity Version: 102019bbffdfd9878649ac2b53a4b3cbf7b.
// - Task ID: 696872113388642b4ed48fda.
// - Task Root ID: 6958e27e4f7767272926ad86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for SearchHistoryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SearchHistoryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  origin_name: string;
  origin_lat: number;
  origin_lng: number;
  destination_name: string;
  destination_lat: number;
  destination_lng: number;
  search_time: string;
}

/**
 * ORM class for SearchHistory entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SearchHistoryORM {
  private static instance: SearchHistoryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b833baaa77582942bb34d2683e028';
    this.entityName = 'search_history';
    this.entityVersion = '102019bbffdfd9878649ac2b53a4b3cbf7b';
    this.taskId = '696872113388642b4ed48fda';
    this.taskRootId = '6958e27e4f7767272926ad86';
  }

  /**
   * Get singleton instance of SearchHistoryORM
   */
  public static getInstance(): SearchHistoryORM {
    if (!SearchHistoryORM.instance) {
      SearchHistoryORM.instance = new SearchHistoryORM();
    }
    
    return SearchHistoryORM.instance;
  }

  /**
   * Get search_history by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSearchHistoryByIDs(ids: string[]): Promise<SearchHistoryModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSearchHistoryByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SearchHistory records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSearchHistory(): Promise<SearchHistoryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SearchHistory record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSearchHistory(data: SearchHistoryModel[]): Promise<SearchHistoryModel[]> {
    const structured = data.map((item) => CreateData(SearchHistoryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SearchHistory records
   */
  async purgeAllSearchHistory(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SearchHistory records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSearchHistory(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SearchHistoryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get search_history by Id index
   * This function gets data by index.
   */
  async getSearchHistoryById(
    id: string,
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) search_history by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSearchHistoryById(
    id: string,
    data: SearchHistoryModel
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const values = SearchHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by Id index
   */
  async deleteSearchHistoryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get search_history by SearchTimeUserId index
   * This function gets data by index.
   */
  async getSearchHistoryBySearchTimeUserId(
    search_time: string,
    user_id: string,
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexSearchTimeUserId(
      search_time,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) search_history by SearchTimeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSearchHistoryBySearchTimeUserId(
    search_time: string,
    user_id: string,
    data: SearchHistoryModel
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexSearchTimeUserId(
      search_time,
      user_id
    );

    const values = SearchHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by SearchTimeUserId index
   */
  async deleteSearchHistoryBySearchTimeUserId(
    search_time: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexSearchTimeUserId(
      search_time,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get search_history by SearchTime index
   * This function gets data by index.
   */
  async getSearchHistoryBySearchTime(
    search_time: string,
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexSearchTime(
      search_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) search_history by SearchTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSearchHistoryBySearchTime(
    search_time: string,
    data: SearchHistoryModel
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexSearchTime(
      search_time
    );

    const values = SearchHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by SearchTime index
   */
  async deleteSearchHistoryBySearchTime(
    search_time: string
  ): Promise<void> {
    const index = createIndexSearchTime(
      search_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get search_history by DataCreator index
   * This function gets data by index.
   */
  async getSearchHistoryByDataCreator(
    data_creator: string,
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) search_history by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSearchHistoryByDataCreator(
    data_creator: string,
    data: SearchHistoryModel
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SearchHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by DataCreator index
   */
  async deleteSearchHistoryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get search_history by DataUpdater index
   * This function gets data by index.
   */
  async getSearchHistoryByDataUpdater(
    data_updater: string,
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) search_history by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSearchHistoryByDataUpdater(
    data_updater: string,
    data: SearchHistoryModel
  ): Promise<SearchHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SearchHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete search_history by DataUpdater index
   */
  async deleteSearchHistoryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SearchHistoryModel data array
   */
  private resultToData(values: Data[]): SearchHistoryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SearchHistoryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SearchHistoryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SearchHistoryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SearchHistoryModel => item !== null);
  }
}

/**
 * Convert SearchHistoryModel data to Value array
 */
function SearchHistoryModelToValues(data: SearchHistoryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'origin_name', type: DataType.string, defaultValue: '' },
    { key: 'origin_lat', type: DataType.number, defaultValue: 0 },
    { key: 'origin_lng', type: DataType.number, defaultValue: 0 },
    { key: 'destination_name', type: DataType.string, defaultValue: '' },
    { key: 'destination_lat', type: DataType.number, defaultValue: 0 },
    { key: 'destination_lng', type: DataType.number, defaultValue: 0 },
    { key: 'search_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SearchHistoryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SearchHistoryModel data
 */
function SearchHistoryModelFromValues(values: Value[]): SearchHistoryModel {
  const data: Partial<SearchHistoryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'origin_name':
        data.origin_name = ParseValue(value, DataType.string) as string;
        break;
      case 'origin_lat':
        data.origin_lat = ParseValue(value, DataType.number) as number;
        break;
      case 'origin_lng':
        data.origin_lng = ParseValue(value, DataType.number) as number;
        break;
      case 'destination_name':
        data.destination_name = ParseValue(value, DataType.string) as string;
        break;
      case 'destination_lat':
        data.destination_lat = ParseValue(value, DataType.number) as number;
        break;
      case 'destination_lng':
        data.destination_lng = ParseValue(value, DataType.number) as number;
        break;
      case 'search_time':
        data.search_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as SearchHistoryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for SearchTimeUserId fields
 */
function createIndexSearchTimeUserId(
  search_time: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, search_time, 'search_time'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['search_time', 'user_id'],
    values
  };
}
/**
 * Create index for SearchTime fields
 */
function createIndexSearchTime(
  search_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, search_time, 'search_time'),
  ];

  return {
    fields: ['search_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SearchHistoryORM;